SENSOR_META = {
    "outsideTemp":         {"offset": 8,   "length": 4, "decode": "hex2int", "factor": 10, "unit": "°C", "device_class": "temperature", "icon": "mdi:thermometer",     "translation_key": "outside_temp"},
    "flowTemp":            {"offset": 12,  "length": 4, "decode": "hex2int", "factor": 10, "unit": "°C", "device_class": "temperature", "icon": "mdi:thermometer",     "translation_key": "flow_temp"},
    "returnTemp":          {"offset": 16,  "length": 4, "decode": "hex2int", "factor": 10, "unit": "°C", "device_class": "temperature", "icon": "mdi:thermometer",     "translation_key": "return_temp"},
    "hotGasTemp":          {"offset": 20,  "length": 4, "decode": "hex2int", "factor": 10, "unit": "°C", "device_class": "temperature", "icon": "mdi:thermometer",     "translation_key": "hotgas_temp"},
    "dhwTemp":             {"offset": 24,  "length": 4, "decode": "hex2int", "factor": 10, "unit": "°C", "device_class": "temperature", "icon": "mdi:water-boiler",     "translation_key": "dhw_temp"},
    "flowTempHC2":         {"offset": 28,  "length": 4, "decode": "hex2int", "factor": 10, "unit": "°C", "device_class": "temperature", "icon": "mdi:thermometer",     "translation_key": "flow_temp_hc2"},
    "evaporatorTemp":      {"offset": 36,  "length": 4, "decode": "hex2int", "factor": 10, "unit": "°C", "device_class": "temperature", "icon": "mdi:snowflake",        "translation_key": "evaporator_temp"},
    "condenserTemp":       {"offset": 40,  "length": 4, "decode": "hex2int", "factor": 10, "unit": "°C", "device_class": "temperature", "icon": "mdi:radiator",         "translation_key": "condenser_temp"},
    "mixerOpen":           {"offset": 45,  "length": 1, "decode": "bit0",    "factor": 1,  "icon": "mdi:gate-open"},
    "mixerClosed":         {"offset": 45,  "length": 1, "decode": "bit1",    "factor": 1,  "icon": "mdi:gate"},
    "heatPipeValve":       {"offset": 45,  "length": 1, "decode": "bit2",    "factor": 1,  "icon": "mdi:valve"},
    "diverterValve":       {"offset": 45,  "length": 1, "decode": "bit3",    "factor": 1,  "icon": "mdi:valve"},
    "dhwPump":             {"offset": 44,  "length": 1, "decode": "bit0",    "factor": 1,  "icon": "mdi:pump"},
    "heatingCircuitPump": {"offset": 44,  "length": 1, "decode": "bit1",    "factor": 1,  "icon": "mdi:pump"},
    "solarPump":           {"offset": 44,  "length": 1, "decode": "bit3",    "factor": 1,  "icon": "mdi:weather-sunny"},
    "compressor":          {"offset": 47,  "length": 1, "decode": "bit3",    "factor": 1,  "icon": "mdi:engine"},
    "boosterStage3":       {"offset": 46,  "length": 1, "decode": "bit0",    "factor": 1},
    "boosterStage2":       {"offset": 46,  "length": 1, "decode": "bit1",    "factor": 1},
    "boosterStage1":       {"offset": 46,  "length": 1, "decode": "bit2",    "factor": 1},
    "highPressureSensor":  {"offset": 49,  "length": 1, "decode": "nbit0",   "factor": 1},
    "lowPressureSensor":   {"offset": 49,  "length": 1, "decode": "nbit1",   "factor": 1},
    "evaporatorIceMonitor":{"offset": 49,  "length": 1, "decode": "bit2",    "factor": 1},
    "signalAnode":         {"offset": 49,  "length": 1, "decode": "bit3",    "factor": 1},
    "evuRelease":          {"offset": 48,  "length": 1, "decode": "bit0",    "factor": 1},
    "ovenFireplace":       {"offset": 48,  "length": 1, "decode": "bit1",    "factor": 1},
    "STB":                 {"offset": 48,  "length": 1, "decode": "bit2",    "factor": 1},
    "outputVentilatorPower":{"offset": 50, "length": 4, "decode": "hex",     "factor": 10, "unit": "W", "icon": "mdi:fan"},
    "inputVentilatorPower":{"offset": 54,  "length": 4, "decode": "hex",     "factor": 10, "unit": "W", "icon": "mdi:fan"},
    "mainVentilatorPower": {"offset": 58,  "length": 4, "decode": "hex",     "factor": 10, "unit": "W", "icon": "mdi:fan"},
    "outputVentilatorSpeed":{"offset": 62, "length": 4, "decode": "hex",     "factor": 1,  "unit": "rpm", "icon": "mdi:speedometer"},
    "inputVentilatorSpeed":{"offset": 66,  "length": 4, "decode": "hex",     "factor": 1,  "unit": "rpm", "icon": "mdi:speedometer"},
    "mainVentilatorSpeed": {"offset": 70,  "length": 4, "decode": "hex",     "factor": 1,  "unit": "rpm", "icon": "mdi:speedometer"},
    "outside_tempFiltered":{"offset": 74,  "length": 4, "decode": "hex2int", "factor": 10, "unit": "°C", "icon": "mdi:thermometer"},
    "relHumidity":         {"offset": 78,  "length": 4, "decode": "hex2int", "factor": 10, "unit": "%", "device_class": "humidity", "icon": "mdi:water-percent"},
    "dewPoint":            {"offset": 82,  "length": 4, "decode": "hex2int", "factor": 10, "unit": "°C", "icon": "mdi:weather-fog"},
    "P_Nd":                {"offset": 86,  "length": 4, "decode": "hex2int", "factor": 100, "unit": "kW", "icon": "mdi:flash"},
    "P_Hd":                {"offset": 90,  "length": 4, "decode": "hex2int", "factor": 100, "unit": "kW", "icon": "mdi:flash"},
    "actualPower_Qc":      {"offset": 94,  "length": 8, "decode": "esp_mant","factor": 1,  "unit": "kW", "icon": "mdi:flash"},
    "actualPower_Pel":     {"offset": 102, "length": 8, "decode": "esp_mant","factor": 1,  "unit": "kW", "icon": "mdi:flash"},
    "collectorTemp":       {"offset": 4,   "length": 4, "decode": "hex2int", "factor": 10, "unit": "°C", "device_class": "temperature", "icon": "mdi:solar-power"},
    "insideTemp":          {"offset": 32,  "length": 4, "decode": "hex2int", "factor": 10, "unit": "°C", "device_class": "temperature", "icon": "mdi:home-thermometer"},
    "windowOpen":          {"offset": 47,  "length": 1, "decode": "bit2",    "factor": 1,  "icon": "mdi:window-open"},
    "quickAirVent":        {"offset": 48,  "length": 1, "decode": "bit3",    "factor": 1,  "icon": "mdi:fan-speed-3"},
    "flowRate":            {"offset": 110, "length": 4, "decode": "hex",     "factor": 100,"unit": "l/min", "icon": "mdi:water-pump"},
    "p_HCw":               {"offset": 114, "length": 4, "decode": "hex",     "factor": 100,"unit": "bar", "icon": "mdi:gauge"},
    "humidityAirOut":      {"offset": 154, "length": 4, "decode": "hex",     "factor": 100,"unit": "%", "device_class": "humidity", "icon": "mdi:water-percent"},
}
